const API_BASE='/api';let authToken=localStorage.getItem('access_token');
function showError(id,msg){const el=document.getElementById(id);if(!el)return;el.innerText=msg;el.style.display='block';setTimeout(()=>{if(el)el.style.display='none'},4000)}
async function apiRequest(endpoint,method,body){const headers={'Content-Type':'application/json'};if(authToken)headers['Authorization']='Bearer '+authToken;const res=await fetch(API_BASE+endpoint,{method,headers,body:body?JSON.stringify(body):undefined});if(res.status===401&&authToken){localStorage.removeItem('access_token');authToken=null;window.location.reload()}return res}
function showAuth(sl){document.getElementById('loginForm').style.display=sl?'block':'none';document.getElementById('registerForm').style.display=sl?'none':'block'}
function logout(){localStorage.removeItem('access_token');authToken=null;document.getElementById('authSection').style.display='block';document.getElementById('chatSection').style.display='none'}
function addMessage(text,isUser){const c=document.getElementById('chatMessages');const d=document.createElement('div');d.className='message '+(isUser?'user-message':'bot-message');d.innerText=text;c.appendChild(d);c.scrollTop=c.scrollHeight}
async function tryAutoLogin(){if(!authToken)return false;try{const res=await apiRequest('/auth/me','GET');if(res.status===200){const d=await res.json();document.getElementById('chatUsername').innerText=d.username;document.getElementById('authSection').style.display='none';document.getElementById('chatSection').style.display='block';return true}}catch(e){}localStorage.removeItem('access_token');authToken=null;return false}
async function register(){const u=document.getElementById('regUsername').value.trim();const p=document.getElementById('regPassword').value;if(!u||!p){showError('regError','Username & password required');return}const btn=document.getElementById('registerBtn');btn.disabled=true;try{const res=await fetch(API_BASE+'/auth/register',{method:'POST',headers:{'Content-Type':'application/json'},body:JSON.stringify({username:u,password:p})});const d=await res.json();if(!res.ok)throw new Error(d.detail||'Registration failed');localStorage.setItem('access_token',d.access_token);authToken=d.access_token;window.location.reload()}catch(err){showError('regError',err.message)}finally{btn.disabled=false}}
async function login(){const u=document.getElementById('loginUsername').value.trim();const p=document.getElementById('loginPassword').value;if(!u||!p){showError('loginError','Enter credentials');return}const btn=document.getElementById('loginBtn');btn.disabled=true;try{const res=await fetch(API_BASE+'/auth/login',{method:'POST',headers:{'Content-Type':'application/json'},body:JSON.stringify({username:u,password:p})});const d=await res.json();if(!res.ok)throw new Error(d.detail||'Invalid login');localStorage.setItem('access_token',d.access_token);authToken=d.access_token;window.location.reload()}catch(err){showError('loginError',err.message)}finally{btn.disabled=false}}
async function sendMessage(){const input=document.getElementById('messageInput');const msg=input.value.trim();if(!msg)return;input.value='';addMessage(msg,true);const btn=document.getElementById('sendBtn');btn.disabled=true;btn.innerText='...';try{const res=await apiRequest('/chat','POST',{message:msg});if(!res.ok)throw new Error((await res.json()).detail||'Chat failed');const d=await res.json();addMessage(d.reply,false)}catch(err){addMessage('⚠️ '+err.message,false)}finally{btn.disabled=false;btn.innerText='Send';input.focus()}}
document.addEventListener('DOMContentLoaded',async()=>{document.getElementById('showRegisterLink')?.addEventListener('click',e=>{e.preventDefault();showAuth(false)});document.getElementById('showLoginLink')?.addEventListener('click',e=>{e.preventDefault();showAuth(true)});document.getElementById('loginBtn')?.addEventListener('click',login);document.getElementById('registerBtn')?.addEventListener('click',register);document.getElementById('sendBtn')?.addEventListener('click',sendMessage);document.getElementById('logoutBtn')?.addEventListener('click',logout);document.getElementById('messageInput')?.addEventListener('keydown',e=>{if(e.key==='Enter'&&!e.shiftKey){e.preventDefault();sendMessage()}});const logged=await tryAutoLogin();if(!logged){document.getElementById('authSection').style.display='block';document.getElementById('chatSection').style.display='none'}else{document.getElementById('authSection').style.display='none';document.getElementById('chatSection').style.display='block'}});
